### ISSUE TITLE
Default output is README.md instead of stdout

### ISSUE THREAD

**Issue by Add00** [cduarte3/f2read#2]
This behavior may make sense, however the -o flag allows the user to specify a file name. It could be beneficial to users have an option to output to the stdout.

**Comment by cduarte3** [comment]
CLI now prints to stdout as well as writing to the README.md or specified file. Giving users a file with the markdown text, as well as being able to copy straight from the terminal.

Also features a name of the repo graphic, displaying F2Read when the program is ran.

Was completed in commit: 6d665c6666ce81e0162fe05d0789f4ea9757fb56
