### ISSUE TITLE
Top level handling of positional arguments

### ISSUE THREAD

**Issue by Add00** [cduarte3/f2read#3]
I really like the way you handle named arguments such as `o`, `m`, or `h`. It is natural and intuitive for a CLI tool. Instead of placing the positional arguments into the sub `new-read` command, you can use `$0` to place it at the top level.

Here is a screenshot of what it could look like.
![image](https://github.com/user-attachments/assets/392f35c7-7bfa-4943-9a94-93ddd622a181)

**Comment by cduarte3** [comment]
Code was fixed to match this approach and was tested and deemed working at the time of writing this comment.

Commit for this issue was: c526f031b1d1c593a006c80a1186d19d474373c1
