### ISSUE TITLE
README.md Issue

### ISSUE THREAD

**Issue by adavis52** [cduarte3/f2read#4]
readMe.md can be README.md instead, bin script setup with bun is not clearly explained. Quotes around 'src' may be unnecessary.

**Comment by cduarte3** [comment]
As per commit: 2a4e17de675709b765a87049464d55c12ca4799e the scripts have been updated.

f2 script no longer requires :

```
bun link
bun link f2read
```

Program can just be ran with bun f2 and any following arguments.

**Comment by cduarte3** [comment]
Quotes on src, ex: 'src' was fixed in commit: f78dffae13d1a143b29a8b50fadafe7f95c3f69e
