### ISSUE TITLE
File path

### ISSUE THREAD

**Issue by adavis52** [cduarte3/f2read#6]
Only files from the src directory can be read. Would be easier for users if they could provide the path.

**Comment by cduarte3** [comment]
Files can now be read from any directory or the src directory by default.

Specifying path such as ./src/filname.py is now a valid argument. Not specifying a path such as simply filename.py is also valid, but the file must be within the src directory to be recognized.

Was done on commit: f78dffae13d1a143b29a8b50fadafe7f95c3f69e
