### ISSUE TITLE
Token Info

### ISSUE THREAD

**Issue by Add00** [cduarte3/f2read#9]
I like your project. If you would like I can I would like to add a token usage flag to the cli tool. This would use the `-t` or `--token-usage` flag and would report additional information to `stderr` including the number of tokens and some other general debug information.

Such as `completion_tokens` the tokens in the response, `prompt_tokens` the number of tokens in the prompt, `total_tokens` the overall amount of tokens. This should be possible to achieve by using the openai and yargs packages.

With your approval I would like to create this feature.

**Comment by cduarte3** [comment]
Yes, you have my approval to go ahead with this.

This sounds like a very useful feature that I am glad you brought to my attention

Thanks.
